---
- hosts: k8s_worker, k8s_control_plane
  tags: cert
  roles:
  - k8s_certs
- hosts: etcd
  tags: etcd
  roles:
  - etcd
- hosts: k8s_control_plane
  serial: 1
  tags: control_plane
  roles:
  - k8s
- hosts: k8s_worker
  serial: 1
  tags: worker
  roles:
  - k8s_worker
