---
- name: Generate The kubelet Kubernetes Configuration File
  when: groups['k8s_worker'] is defined and inventory_hostname in groups['k8s_worker']
  shell: > 
    kubectl config set-cluster {{ cluster_name }} \
    --certificate-authority=ca.pem \
    --embed-certs=true \
    --server=https://{{ kubernetes_public_address }}:6443 \
    --kubeconfig={{ inventory_hostname_short }}.kubeconfig

- name: Generate The kubelet Kubernetes Configuration File
  when: groups['k8s_worker'] is defined and inventory_hostname in groups['k8s_worker']
  shell: > 
    kubectl config set-credentials system:node:{{ inventory_hostname_short }} \
    --client-certificate={{ inventory_hostname_short }}.pem \
    --client-key={{ inventory_hostname_short }}-key.pem \
    --embed-certs=true \
    --kubeconfig={{ inventory_hostname_short }}.kubeconfig

- name: Generate The kubelet Kubernetes Configuration File
  when: groups['k8s_worker'] is defined and inventory_hostname in groups['k8s_worker']
  shell: > 
    kubectl config set-context default \
    --cluster={{ cluster_name }} \
    --user=system:node:{{ inventory_hostname_short }} \
    --kubeconfig={{ inventory_hostname_short }}.kubeconfig

- name: Generate The kubelet Kubernetes Configuration File
  when: groups['k8s_worker'] is defined and inventory_hostname in groups['k8s_worker']
  shell: > 
    kubectl config use-context default --kubeconfig={{ inventory_hostname_short }}.kubeconfig
     

...