---
- name: Create a temp directory if it does not exist
  file:
    path: "{{ cert_dir }}"
    state: directory
    mode: '0755'

- name: render ca-csr.json
  run_once: True
  delegate_to: "{{ certgen_host }}"
  template:
    src: ca-csr.j2
    dest: "{{ cert_dir }}/ca-csr.json"
  notify: "ca cert"

- name: render ca-requestheader-client-csr.json
  run_once: True
  delegate_to: "{{ certgen_host }}"
  template:
    src: ca-requestheader-client-csr.j2
    dest: "{{ cert_dir }}/ca-requestheader-client-csr.json"
  notify: "ca requestheader cert"

- name: render ca-config.json
  run_once: True
  delegate_to: "{{ certgen_host }}"
  template:
    src: ca-config.j2
    dest: "{{ cert_dir }}/ca-config.json"
  notify: "ca cert"

- name: render admin-csr.json
  run_once: True
  delegate_to: "{{ certgen_host }}"
  template:
    src: admin-csr.j2
    dest: "{{ cert_dir }}/admin-csr.json"
  notify: Generate The Admin Client Certificate

- name: render kube-controller-manager-csr.json
  run_once: True
  delegate_to: "{{ certgen_host }}"
  template:
    src: kube-controller-manager-csr.j2
    dest: "{{ cert_dir }}/kube-controller-manager-csr.json"
  notify: Generate The Controller Manager Client Certificate

- name: render kube-proxy-csr.json
  run_once: True
  delegate_to: "{{ certgen_host }}"
  template:
    src: kube-proxy-csr.j2
    dest: "{{ cert_dir }}/kube-proxy-csr.json"
  notify: Generate The Kube Proxy Client Certificate

- name: render kube-scheduler-csr.json
  run_once: True
  delegate_to: "{{ certgen_host }}"
  template:
    src: kube-scheduler-csr.j2
    dest: "{{ cert_dir }}/kube-scheduler-csr.json"
  notify: Generate The Scheduler Client Certificate

- name: render kubernetes-csr.json
  run_once: True
  delegate_to: "{{ certgen_host }}"
  template:
    src: kubernetes-csr.j2
    dest: "{{ cert_dir }}/kubernetes-csr.json"
  notify: Generate The Kubernetes API Server Certificate

- name: render front-proxy-client-csr.json
  run_once: True
  delegate_to: "{{ certgen_host }}"
  template:
    src: front-proxy-client-csr.j2
    dest: "{{ cert_dir }}/front-proxy-client-csr.json"
  notify: Generate The Front Proxy Client Certificate
  
- name: render The Kubelet Client csr
  run_once: True
  delegate_to: "{{ certgen_host }}"
  template:
    src: instance-csr.j2
    dest: "{{ cert_dir }}/{{ item }}-csr.json"
  with_items: "{{ groups['k8s_worker'] }}"
  notify:
    - Generating The Kubelet Client Certificates

- name: render service-account-csr.json
  run_once: True
  delegate_to: "{{ certgen_host }}"
  template:
    src: service-account-csr.j2
    dest: "{{ cert_dir }}/service-account-csr.json"
  notify: Generate The Kubernetes Service Account Certificate

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
...