---
- name: Install loadbalancer for Kube-Api (haproxy)
  package:
    name: haproxy
    state: present
  notify:
    - enable haproxy

- name: Render haproxy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: 
    - reload haproxy
...