---
- name: Add modules
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
  - overlay
  - br_netfilter
  
- name: Enable ip forward
  sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
  - net.bridge.bridge-nf-call-iptables
  - net.ipv4.ip_forward
  - net.bridge.bridge-nf-call-ip6tables

...