---
- name: "daemon-reload"
  systemd:
    daemon_reload: yes

- name: "restart control plane"
  systemd:
    name: "{{ item }}"
    state: restarted
  with_items:
  - kube-apiserver.service
  - kube-controller-manager.service
  - kube-scheduler.service

- name: "restart apiserver"
  systemd:
    name: kube-apiserver
    state: restarted

- name: "restart controller_manager"
  systemd:
    name: kube-controller-manager
    state: restarted

- name: "restart scheduler"
  systemd:
    name: kube-scheduler
    state: restarted

- name: "enable apiserver"
  systemd:
    name: kube-apiserver.service
    enabled: yes

- name: "enable scheduler"
  systemd:
    name: kube-scheduler.service
    enabled: yes

- name: "enable controller_manager"
  systemd:
    name: kube-controller-manager.service
    enabled: yes